default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  
  # username: postgres
  # password: 
  # host: db
  
  username: yaro
  password: pass
  host:     <%= ENV['IP'] %>
  

development:
  <<: *default
  database: tddrails_development

test:
  <<: *default
  database: tddrails_test

production:
  <<: *default
  database: tddrails_production